export const paragraphs = [
  'Alegreya',
  'Asap',
  'Average',
  'Cabin',
  'Cardo',
  'Crete Round',
  'Crimson Text',
  'Domine',
  'Droid Sans',
  'Droid Serif',
  'Exo',
  'Gentium Book Basic',
  'Josefin Slab',
  'Kreon',
  'Lora',
  'Libre Baskerville',
  'Merriweather',
  'Neuton',
  'Noticia Text',
  'Old Standard TT',
  'Open Sans',
  'Poly',
  'PT Sans',
  'PT Serif',
  'Roboto',
  'Source Sans Pro',
  'Ubuntu',
  'Varela',
  'Vollkorn',
  'Work Sans',
]
export const headings = [
  'Abel',
  'Arvo',
  'Bitter',
  'Bree Serif',
  'Cabin',
  'Droid Sans',
  'Droid Serif',
  'Gudea',
  'Istok Web',
  'Lato',
  'Lobster',
  'Merriweather',
  'Montserrat',
  'Muli',
  'Nunito',
  'Open Sans',
  'Oswald',
  'Pacifico',
  'Playfair Display',
  'PT Sans',
  'PT Serif',
  'Quicksand',
  'Raleway',
  'Roboto',
  'Roboto Slab',
  'Rokkitt',
  'Ubuntu',
  'Varela',
  'Vollkorn',
  'Work Sans',
]
export const texts = [
  'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz 0123456789',
  'fontName',
  'Grumpy wizards make toxic brew for the evil Queen and Jack.',
  'Bright vixens jump dozy fowl quack',
  'Waltz bad nymph for quick jugs vex',
  'Brick quiz whangs jumpy veldt fox',
  'The quick brown fox jumps over the lazy dog.',
]
export const groupSize = 900

export const weightLabels = {
  100: 'Thin',
  200: 'Extra-Light',
  300: 'Light',
  400: 'Normal',
  500: 'Medium',
  600: 'Semi-Bold',
  700: 'Bold',
  800: 'Extra-Bold',
  900: 'Ultra-Bold'
};

